name: mxc_logic
description: MXC shared logic library
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  chopper: ^4.0.5
  decimal: ^2.3.2
  meta: ^1.8.0
  path: ^1.8.2
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  collection: ^1.17.0
  http: ^0.13.5
  rxdart: ^0.27.7
  json_annotation: ^4.4.0
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.23.1
  dotenv: ^4.1.0
  
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.4
  swagger_dart_code_generator: 
    git: https://github.com/festelo/swagger-dart-code-generator.git
  build_runner: ^2.3.3
