name: mxc_logic
description: MXC shared logic library
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  built_collection: ^5.1.1
  built_value: ^8.4.4
  chopper: ^6.1.3
  collection: ^1.17.0
  decimal: ^2.3.2
  ed25519_hd_key: ^2.2.0
  ens_dart:
    path: ../../ens_dart
  eth_sig_util: ^0.0.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  googleapis: ^11.0.0
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  hex: ^0.2.0
  http: ^0.13.5
  http_interceptor: ^1.0.1
  icloud_storage: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  meta: ^1.8.0
  path: ^1.8.2
  path_provider: ^2.0.12
  phoenix_socket: ^0.7.6
  rxdart: ^0.27.0
  sembast: ^3.4.0+6
  sembast_web: ^2.1.0+4
  web3dart: ^2.3.3

dependency_overrides:
  # Graphql 5.1.3 requires this version so we override this
  # for phoenix_socket to use lower version of ws
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.1
  flutter_lints: ^2.0.1
  json_serializable: ^6.1.4
  test: ^1.23.1
  web3dart_builders: ^0.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/cache/MEP-1759-DApp-store/
    - assets/cache/MEP-1759-DApp-store/dapp_store/
    - assets/cache/MEP-1759-DApp-store/mxc_dapps_thumbnails/
    - assets/cache/MEP-1759-DApp-store/mxc_dapps_thumbnails/icons_v3/
    - assets/cache/wannseeswap-tokenlist/
    - assets/cache/wannseeswap-tokenlist/assets/
    - assets/cache/ipfs-gateway-list/
    - assets/cache/mxc-tweets-list/
