name: mxc_ui
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_i18n: ^0.35.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.1
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.5
  rxdart: ^0.27.0
  super_tooltip: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
    - family: SpaceX
      fonts:
        - asset: assets/fonts/SpaceX.ttf
